name: Sign PowerShell Scripts

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - sign-test

jobs:
  sign_scripts:
    name: Sign PowerShell scripts
    runs-on: windows-2022
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Sign powershell script
        shell: powershell
        env:
          PFX_CERT: ${{ secrets.PFX_CERT }}
        run: |
          Set-Content -Value $([System.Convert]::FromBase64String($env:PFX_CERT)) -Path .\mondoo_code_signing_cert.pfx -Encoding Byte
          
          # sign install.sh and ensure proper encoding as UTF8 NoBOM
          $filename = 'install.ps1'
          Set-AuthenticodeSignature -Certificate (Get-PfxCertificate -FilePath .\mondoo_code_signing_cert.pfx) -FilePath $filename -TimestampServer 'http://timestamp.digicert.com' -HashAlgorithm 'SHA256'
          $content = Get-Content -Raw $filename
          [IO.File]::WriteAllLines($filename, $content)

          # sign install.sh and ensure proper encoding as UTF8 NoBOM
          $filename = 'download.ps1'
          Set-AuthenticodeSignature -Certificate (Get-PfxCertificate -FilePath .\mondoo_code_signing_cert.pfx) -FilePath $filename -TimestampServer 'http://timestamp.digicert.com' -HashAlgorithm 'SHA256'
          $content = Get-Content -Raw $filename
          [IO.File]::WriteAllLines($filename, $content)

          # commit changes
          git config --global user.email "tools@mondoo.com"
          git config --global user.name "Mondoo Tools"
          git add install.ps1
          git add download.ps1
          git commit -m "Sign powershell scripts"
          git push
